In [1]:
def add(a, b):
  return a+b

In [2]:
x = 10
y = 20
res = add(x,y)
print("sum =", res)

sum = 30


In [3]:
def welcome():
 print("Welcome to Python Lab")
welcome()

Welcome to Python Lab


In [4]:
def sq(n):
  return n*n
print(sq(5))

25


In [6]:
import numpy as np
n = int(input("How many numbers?"))
number = []
for i in range(n):
  x = int(input("Enter number:"))
  number.append(x)
arr = np.array(number)
print("Numpy Array:", arr)
print("Array type:", type(arr))
print("Numpy Array type", arr.dtype)
print("Numpy Array type", arr.shape)
print("Numpy Array dimension", arr.ndim)

How many numbers?4
Enter number:1
Enter number:2
Enter number:3
Enter number:4
Numpy Array: [1 2 3 4]
Array type: <class 'numpy.ndarray'>
Numpy Array type int64
Numpy Array type (4,)
Numpy Array dimension 1


In [12]:
def create_array(n):
  number = []
  for i in range(n):
    x = int(input("Enter number:"))
    number.append(x)
  return np.array(number)

In [13]:
n = int(input("How many numbers?"))
arr = create_array(n)
print("Numpy Array:", arr)
print("Array type:", type(arr))
print("Numpy Array type", arr.dtype)
print("Numpy Array type", arr.shape)
print("Numpy Array dimension", arr.ndim)

How many numbers?4
Enter number:1
Enter number:2
Enter number:3
Enter number:4
Numpy Array: [1 2 3 4]
Array type: <class 'numpy.ndarray'>
Numpy Array type int64
Numpy Array type (4,)
Numpy Array dimension 1


#Default Arguments

In [19]:
def student(name, age):
  print("Name:", name)
  print("Age:", age)

In [20]:
def student(name, age=21):
  print("Name:", name)
  print("Age:", age)

In [21]:
student("Raj",25)
student("Varun")

Name: Raj
Age: 25
Name: Varun
Age: 21


#Required Argument

In [23]:
def printInfo(name, age):
  print("Name:", name)
  print("Age:", age)

In [27]:
printInfo("Raj",21)

Name: Raj
Age: 21


#Keyword Argument

In [28]:
def printInfo(name, age):
  print("Name:", name)
  print("Age:", age)

In [29]:
printInfo(name ="Raj", age=21)

Name: Raj
Age: 21


In [30]:
printInfo(age = 21, name = "Raj")

Name: Raj
Age: 21


#Variable Length Argument (*argument)

In [31]:
def add(a,b):
  print(a+b)

In [33]:
def add(*num):
  total = 0
  for n in num:
    total += n
  print(total)

In [34]:
add(10,20)
add(10,20,30,40,50)

30
150


#Variable length Argument (**kwargs)

In [35]:
def student(**details):
  print(details)
student(name ="Raj", age = 21, course = "python")

{'name': 'Raj', 'age': 21, 'course': 'python'}


In [36]:
def calculate(a, b):
  return a+b, a-b, a*b

s, d, m = calculate(10,5)
print("Sum", s)
print("Diiference", d)
print("Multiplication", m)

Sum 15
Diiference 5
Multiplication 50


#Reshaping Array

In [37]:
data = np.arange(1,13)
a = data.reshape(3,4)
b = data.reshape(4,3)
c = data.reshape(2, -1)
print(f'1D:{data}')
print(f'3x4:\n{a}')
print(f'4x3:\n{b}')
print(f'2xinfer:\n{c}')

print(f'A shape:\n{a.shape}')
print(f'B shape:\n{b.shape}')
print(f'C shape:\n{c.shape}')

1D:[ 1  2  3  4  5  6  7  8  9 10 11 12]
3x4:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
4x3:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
2xinfer:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
A shape:
(3, 4)
B shape:
(4, 3)
C shape:
(2, 6)


#Make a function to take input from user and reshape numpy array into 6x2 matrix 3x-1 matrix and 5x-1 matrix. If error comes please explain the error.

In [38]:
def reshape_user_input():
    try:
        arr = np.array([float(x) for x in input("Numbers: ").split()])
    except ValueError:
        print("Error: Invalid numbers input.")
        return

    n = arr.size
    for shape in [(6, 2), (3, -1), (5, -1)]:
        try:
            print(f"Shape {shape}:\n{arr.reshape(shape)}\n")
        except ValueError:
            req = shape[0] if shape[1] == -1 else shape[0] * shape[1]
            if shape[1] == -1:
                print(f"Error for {shape}: Total elements ({n}) must be divisible by {req}.\n")
            else:
                print(f"Error for {shape}: Requires exactly {req} elements, got {n}.\n")

reshape_user_input()

Numbers: 5
Error for (6, 2): Requires exactly 12 elements, got 1.

Error for (3, -1): Total elements (1) must be divisible by 3.

Error for (5, -1): Total elements (1) must be divisible by 5.



# flatten() and ravel()

In [40]:
data = np.array([[[1,2,3],[4,5,6]]])
print("Data shape:", data.ndim)
flat1 = data.flatten()
print("Data shape:", flat1.ndim)
flat2 = data.ravel()
print("Data shape:", flat2.ndim)

Data shape: 3
Data shape: 1
Data shape: 1


#np.concatenate()
#np.vstack()
#np.hstack()

In [41]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(f'concatenate:{np.concatenate((a,b))}')
print(f'vstack:{np.vstack((a,b))}')
print(f'hstack:{np.hstack((a,b))}')

concatenate:[1 2 3 4 5 6]
vstack:[[1 2 3]
 [4 5 6]]
hstack:[1 2 3 4 5 6]


In [48]:
import numpy as np
data = np.array([10,20,30,40,50])
result = []
for x in data:
  result.append(x*2)
print(f'loop array: {result}')

loop array: [np.int64(20), np.int64(40), np.int64(60), np.int64(80), np.int64(100)]


In [50]:
vec_result = data * 2
print(f'Vec array: {vec_result}')

Vec array: [ 20  40  60  80 100]


In [52]:
a = np.array([10,20,30])
b = np.array([2,4,5])
print("Addition", a+b)
print("Subtraction", a-b)
print("Multiplication", a*b)
print("Division", a/b)
print("Modulus", a%b)

Addition [12 24 35]
Subtraction [ 8 16 25]
Multiplication [ 20  80 150]
Division [5. 5. 6.]
Modulus [0 0 0]


In [55]:
marks = np.array([50,60,70,80,90])
print(f'Add 5:{marks+5}')
print(f'Sub 5:{marks-5}')
print(f'Mul 5:{marks*5}')
print(f'Div 5:{marks/5}')
print(f'Mod 5:{marks%5}')
print(f'Sub 10:{marks-10}')
print(f'Double:{marks*2}')
print(f'Half:{marks/2}')

Add 5:[55 65 75 85 95]
Sub 5:[45 55 65 75 85]
Mul 5:[250 300 350 400 450]
Div 5:[10. 12. 14. 16. 18.]
Mod 5:[0 0 0 0 0]
Sub 10:[40 50 60 70 80]
Double:[100 120 140 160 180]
Half:[25. 30. 35. 40. 45.]


In [60]:
print(f'sqrt:{np.sqrt(marks)}')
print(f'sin:{np.sin(marks)}')
print(f'cos:{np.cos(marks)}')
print(f'tan:{np.tan(marks)}')
print(f'square:{np.square(marks)}')
print(f'log:{np.log(marks)}')
print(f'exp:{np.exp(marks)}')
print(f'max:{np.max(marks)}')
print(f'min:{np.min(marks)}')
print(f'sum:{np.sum(marks)}')
print(f'mean:{np.mean(marks)}')
print(f'median:{np.median(marks)}')
print(f'std:{np.std(marks)}')

sqrt:[7.07106781 7.74596669 8.36660027 8.94427191 9.48683298]
sin:[-0.26237485 -0.30481062  0.77389068 -0.99388865  0.89399666]
cos:[ 0.96496603 -0.95241298  0.6333192  -0.11038724 -0.44807362]
tan:[-0.27190061  0.32004039  1.22195992  9.00365495 -1.99520041]
square:[2500 3600 4900 6400 8100]
log:[3.91202301 4.09434456 4.24849524 4.38202663 4.49980967]
exp:[5.18470553e+21 1.14200739e+26 2.51543867e+30 5.54062238e+34
 1.22040329e+39]
max:90
min:50
sum:350
mean:70.0
median:70.0
std:14.142135623730951


#Broadcasting

In [61]:
arr = np.array([1,2,3])
res = arr+1
print(res)

[2 3 4]


In [63]:
a = np.array([2,4,6])
b = np.array(([1,3,5],[7,9,11]))
res = a + b
print(res)

[[ 3  7 11]
 [ 9 13 17]]


#Broadcasting in Conditional Operation

In [65]:
a = np.array([12,34,35,45,60,72])
b = np.array(["Adult","Minor"])
res = np.where(a>18, b[0], b[1])
print(res)

['Minor' 'Adult' 'Adult' 'Adult' 'Adult' 'Adult']


#Broadcasting for Matrix Multiplication

In [68]:
m = np.array([[1,2],[3,4]])
v = np.array([10,20])
res = m*v
res = v*m
print(res)

[[10 40]
 [30 80]]
