In [5]:
num = int(input("enter an integer"))
print(type(num))

enter an integer5
<class 'int'>


In [6]:
for i in range(1,11):
  print(f'{num} x {i} = {num *i}')

5 x 1 = 5
5 x 2 = 10
5 x 3 = 15
5 x 4 = 20
5 x 5 = 25
5 x 6 = 30
5 x 7 = 35
5 x 8 = 40
5 x 9 = 45
5 x 10 = 50


In [7]:
num=(input("enter an integer"))
print(type(num))

enter an integer5
<class 'str'>


In [8]:
for i in range(1,11):
  print(f'{num} x {i} = {num *i}')

5 x 1 = 5
5 x 2 = 55
5 x 3 = 555
5 x 4 = 5555
5 x 5 = 55555
5 x 6 = 555555
5 x 7 = 5555555
5 x 8 = 55555555
5 x 9 = 555555555
5 x 10 = 5555555555


In [9]:
a = float(input("Enter first number"))
b = float(input("Enter second number"))
print(f'The sum of {a} and {b} is {a+b}')
print(f'Substraction:{a-b}')
print(f'Multiplication:{a*b}')
print(f'Division:{a/b}')
print(f'Floor Division:{a//b}')
print(f'Modulus:{a%b}')
print(f'Exponenetial:{a**b}')

Enter first number17.9
Enter second number4.5
The sum of 17.9 and 4.5 is 22.4
Substraction:13.399999999999999
Multiplication:80.55
Division:3.9777777777777774
Floor Division:3.0
Modulus:4.399999999999999
Exponenetial:434348.8134104658


In [11]:
nums = [12,14,19,10,20]
tot = 0
for x in nums:
  tot = tot+x
avg = tot/len(nums)
print(f'Total:{tot}')
print(f'Average:{avg}')

Total:75
Average:15.0


In [59]:
import numpy as np

In [17]:
marks = np.array([72.0,'False',81,54,90])
print("Array:", marks)
print("Type:", type(marks))

Array: ['72.0' 'False' '81' '54' '90']
Type: <class 'numpy.ndarray'>


In [20]:
a0d = np.array(46)
print(f'Array:{a0d}')
print(f'Type:{a0d.dtype}')
print(f'ndim:{a0d.ndim}')
print(f'shape:{a0d.shape}')
print(f'size:{a0d.size}')

Array:46
Type:int64
ndim:0
shape:()
size:1


In [21]:
a0d = np.array([72.0,45.1,81,54,90])
print(f'Array:{a0d}')
print(f'Type:{a0d.dtype}')
print(f'ndim:{a0d.ndim}')
print(f'shape:{a0d.shape}')
print(f'size:{a0d.size}')

Array:[72.  45.1 81.  54.  90. ]
Type:float64
ndim:1
shape:(5,)
size:5


In [23]:
a2d = np.array([[1,2,3],[4,5,6]])
print(f'Array:{a2d}')
print(f'Type:{a2d.dtype}')
print(f'ndim:{a2d.ndim}')
print(f'shape:{a2d.shape}')
print(f'size:{a2d.size}')

Array:[[1 2 3]
 [4 5 6]]
Type:int64
ndim:2
shape:(2, 3)
size:6


In [24]:
a3d = np.array([[1,2,3],[4,5,6],[14,15,16]])
print(f'Array:{a3d}')
print(f'Type:{a3d.dtype}')
print(f'ndim:{a3d.ndim}')
print(f'shape:{a3d.shape}')
print(f'size:{a3d.size}')

Array:[[ 1  2  3]
 [ 4  5  6]
 [14 15 16]]
Type:int64
ndim:2
shape:(3, 3)
size:9


#Create 3d array of shape 2,3,3 check it by printing its dimension and shape

In [50]:


array_3d = np.zeros((2, 3, 3))

print("Array:")
print(array_3d)

print("\nDimension (ndim):", array_3d.ndim)
print("Shape:", array_3d.shape)


Array:
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]

Dimension (ndim): 3
Shape: (2, 3, 3)


In [29]:
print('a2d[0]')

a2d[0]


In [33]:
print(f'Array:{a2d}')
print(f'row1, col1:{a2d[0,0]}')
print(f'row1, col2:{a2d[0,1]}')

Array:[[1 2 3]
 [4 5 6]]
row1, col1:1
row1, col2:2


In [44]:
print(f'Array:{a2d}')
print(f'row1, col1:{a2d[0,0]}')
print(f'row2, col3:{a2d[1,1]}')
print(f'Second row:{a2d[1,:]}')
print(f'Second column:{a2d[:,1]}')
print(f'First row:{a2d[0,:]}')
print(f'First column:{a2d[:,0]}')
print(f'Type:{a2d.dtype}')
print(f'ndim:{a2d.ndim}')
print(f'shape:{a2d.shape}')
print(f'size:{a2d.size}')

Array:[[1 2 3]
 [4 5 6]]
row1, col1:1
row2, col3:5
Second row:[4 5 6]
Second column:[2 5]
First row:[1 2 3]
First column:[1 4]
Type:int64
ndim:2
shape:(2, 3)
size:6


In [47]:
print(f'Array:{a3d}')
print(f'row1, col1:{a3d[0,0]}')
print(f'row1, col2:{a3d[0,1]}')

Array:[[ 1  2  3]
 [ 4  5  6]
 [14 15 16]]
row1, col1:1
row1, col2:2


In [53]:
print(f'Array;{a0d}')

Array;[72.  45.1 81.  54.  90. ]


In [54]:
print(f'First fouro elements:{a0d[:4]}')
print(f'First 3 elements:{a0d[:3]}')
print(f'Last 3 elements:{a0d[3:]}')
print(f'Last 3 elements:{a0d[-2:]}')
print(f'Reverse:{a0d[::-1]}')
print(f'Middle:{a0d[2:5]}')
print(f'Every second value:{a0d[::2]}')

First fouro elements:[72.  45.1 81.  54. ]
First 3 elements:[72.  45.1 81. ]
Last 3 elements:[54. 90.]
Last 3 elements:[54. 90.]
Reverse:[90.  54.  81.  45.1 72. ]
Middle:[81. 54. 90.]
Every second value:[72. 81. 90.]


#Write a program to take 12 elements in an array and reverse only the first six values

In [58]:
arr = np.array([int(x) for x in input("Enter 12 numbers: ").split()])
print(arr[:6][::-1])

Enter 12 numbers: 12 45 32 34 67 56 43 13 29 50 67 88
[56 67 34 32 45 12]


In [60]:
ze = np.zeros(5)
print(ze)
print(f'Type:{ze.dtype}')
print(f'ndim:{ze.ndim}')
print(f'shape:{ze.shape}')
print(f'size:{ze.size}')

[0. 0. 0. 0. 0.]
Type:float64
ndim:1
shape:(5,)
size:5


In [63]:
one = np.ones((2,3), dtype=int)
print(one)
print(f'Type:{one.dtype}')
print(f'ndim:{one.ndim}')
print(f'shape:{one.shape}')
print(f'size:{one.size}')

[[1 1 1]
 [1 1 1]]
Type:int64
ndim:2
shape:(2, 3)
size:6


In [62]:
full = np.full((2,3),7)
print(full)
print(f'Type:{full.dtype}')
print(f'ndim:{full.ndim}')
print(f'shape:{full.shape}')
print(f'size:{full.size}')

[[7 7 7]
 [7 7 7]]
Type:int64
ndim:2
shape:(2, 3)
size:6


#create a 4 cross 2 matrix filled with 100


In [64]:
matrix = np.full((4,2),100)
print(matrix)

[[100 100]
 [100 100]
 [100 100]
 [100 100]]


#Generating sequence with arange() and linspace()

In [71]:
a = np.arange(0, 10, 2)
print(a)

[0 2 4 6 8]


In [73]:
b = np.linspace(1, 20, 6)
print(b)

[ 1.   4.8  8.6 12.4 16.2 20. ]


#Random number generation

In [83]:
np.random.seed(42)
print(f'Random decimal:{np.random.random(5)}')

Random decimal:[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]


In [87]:
print(f'{np.random.rand(2,3)}')

[[0.61748151 0.61165316 0.00706631]
 [0.02306243 0.52477466 0.39986097]]


In [86]:
print(f'Random Integer:{np.random.randint(1,11, size=(3,3))}')

Random Integer:[[8 3 6]
 [5 2 8]
 [6 2 5]]
